
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unir_db
    username: root
    password: Dnlcan92**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

    spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fandanie/config-repo
